In [5]:
import pandas as pd
import numpy as np

## Introducing Pandas Objects

### The Pandas Series Object

In [7]:
# 1d array of indexed data
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [8]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [10]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [11]:
data[1]

0.5

In [13]:
data[1:3]

1    0.50
2    0.75
dtype: float64

#### Series as a generalized NumPy array

In [17]:
# numpy array has implicit integer index, series has explicit defined
# series index doesnt have to be an integer
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])

data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

#### Constructing Series objects

In [19]:
pd.Series([2,4,6])

0    2
1    4
2    6
dtype: int64

In [20]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [21]:
# can be a dict
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [22]:
# index can be explicitly set
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3,2])

3    c
2    a
dtype: object

## The Pandas DataFrame Object

### DataFrame as a generalized NumPy array

In [4]:
population_dict = {'California': 38332521,
                               'Texas': 26448193,
                               'New York': 19651127,
                               'Florida': 19552860,
                               'Illinois': 12882135}
population = pd.Series(population_dict)

area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
                 'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)

In [6]:
states = pd.DataFrame({'population': population,
                       'area': area})

In [7]:
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [8]:
# has an index, like series
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [9]:
# also has a columns attribute, which is an Index object of col labels
states.columns

Index(['population', 'area'], dtype='object')

### DataFrame as specialized dictionary

In [10]:
# DataFrame maps a colu,n name to a `Series` of column data
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

### Constructing DataFrame objects

#### From a single Series object

In [11]:
pd.DataFrame(population, columns=['population'])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

#### From a list of dicts

In [12]:
data = [{'a': i, 'b': 2 * i} for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [14]:
# pandas will fill in missing keys with NaN
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

#### From a dictionary of Series objects

In [15]:
pd.DataFrame({'population': population,
              'area': area})

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

#### From a two-dimensional NumPy array

In [16]:
pd.DataFrame(np.random.rand(3, 2),
            columns = ['foo', 'bar'],
            index = ['a', 'b', 'c'])

foo       bar
a  0.602065  0.039842
b  0.117191  0.037854
c  0.219023  0.268995

#### From a NumPy structured array

In [19]:
A = np.zeros(3, dtype = [('A', 'i8'), ('B', 'f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [20]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

## The Pandas Index Object

In [23]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

### Index as immutable array

In [25]:
ind[1]

3

In [27]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [28]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


In [29]:
# cant modify
ind[1] = 0

TypeError: Index does not support mutable operations

#### Index as ordered set

In [31]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [32]:
indA & indB

Int64Index([3, 5, 7], dtype='int64')

In [33]:
indA | indB

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [35]:
indA ^ indB # symmetric difference

Int64Index([1, 2, 9, 11], dtype='int64')

## Data Indexing and Selection

### Data Selection in Series

#### Series as dictionary

In [38]:
data = pd.Series([0.2, 0.5, 0.7, 1.0], index = ['a', 'b', 'c', 'd'])

In [39]:
data

a    0.2
b    0.5
c    0.7
d    1.0
dtype: float64

In [41]:
data['b']

0.5

In [42]:
'a' in data

True

In [43]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [45]:
list(data.items())

[('a', 0.2), ('b', 0.5), ('c', 0.7), ('d', 1.0)]

In [46]:
# can modify series, assign new index value
data['e'] = 1.25

#### Series as one-dimensinal array

In [47]:
# slicing by explicit index
data['a':'c']

a    0.2
b    0.5
c    0.7
dtype: float64

In [48]:
# slicing by implicit integer index
data[0:2]

a    0.2
b    0.5
dtype: float64

In [49]:
# masking
data[(data > 0.3) & (data < 0.8)]

b    0.5
c    0.7
dtype: float64

In [50]:
# fancy indexing
data[['a', 'e']]

a    0.20
e    1.25
dtype: float64

### Indexers: loc, iloc, and ix

In [51]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])

In [52]:
# explicit when indexing
data[1]

'a'

In [55]:
# implicit index when slicing
data[1:3]

3    b
5    c
dtype: object

In [56]:
# loc always references explicit index
data.loc[1]

'a'

In [57]:
data.loc[1:3]

1    a
3    b
dtype: object

In [58]:
# iloc references implicit index, ie 0,1,2
data.iloc[1:3]

3    b
5    c
dtype: object

## Data Selection in DataFrame

In [60]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                          'New York': 141297, 'Florida': 170312,
                          'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                         'New York': 19651127, 'Florida': 19552860,
                         'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [61]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [62]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [63]:
data.area is data['area']

True

In [64]:
# if column names conflict with method name, not possible
data.pop is data['pop']
# In particular, you should avoid the temptation to
# try column assignment via attribute (i.e., use data['pop'] = z rather than data.pop = z).

False

In [65]:
data['density'] = data['pop'] / data['area']

### DataFrame as 2d array

In [66]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [67]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [68]:
# passing single index accesses a row
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [69]:
# passing single index accesses a column
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [70]:
data.iloc[:3, :2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [71]:
data.loc[:'Illinois', :'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

# Operating on Data in Pandas

### Ufuncs: Index Preservation

In [73]:
# any NumPy ufunc will work on Pandas Series and DataFrame objects
import pandas as pd
import numpy as np

In [75]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int64

In [76]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
                  columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [77]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [78]:
np.sin(df * np.pi / 4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

### Ufuncs: Index Alignment
* For binary operations, Pandas will align indices in the process of performing the operation 

#### Index alignment in Series

* Combine two data sources, find the top three US states by area and by population

In [79]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')

In [81]:
# preserves the union of indices of two input arrays
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [82]:
area.index | population.index

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

#### Index alignment in DataFrame

* similar alignment takes place for both columns and indices when applied to dataframe

In [115]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
                 columns=list('AB'))

In [106]:
A

A  B
0  1  5
1  9  3

In [107]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
                 columns=list('BAC'))
B

B  A  C
0  5  1  9
1  1  9  3
2  7  6  8

In [108]:
A + B

A     B   C
0   2.0  10.0 NaN
1  18.0   4.0 NaN
2   NaN   NaN NaN

In [116]:
A.stack().mean()

6.5

In [118]:
# fill with all mean values of A by stacking the rows
fill = A.stack().mean()
print(fill)
A.add(B, fill_value=fill)

6.5


A     B     C
0  13.0   5.0  15.5
1  15.0   9.0   9.5
2  12.5  13.5  14.5

## Ufuncs: Operations Between DataFrame and Series

* Operations between DataFrame and Series are similar to operations between a two-dimensional and one-dimensional array

#### Find difference between a 2d array and one of its rows

In [130]:
rng.seed(2)
A = rng.randint(10, size = (3, 4))
A

array([[8, 8, 6, 2],
       [8, 7, 2, 1],
       [5, 4, 4, 5]])

In [131]:
# applied row-wise
A - A[0]

array([[ 0,  0,  0,  0],
       [ 0, -1, -4, -1],
       [-3, -4, -2,  3]])

In [135]:
df = pd.DataFrame(A, columns=list('QRST'))
df

Q  R  S  T
0  8  8  6  2
1  8  7  2  1
2  5  4  4  5

In [137]:
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1  0 -1 -4 -1
2 -3 -4 -2  3

In [140]:
# column-wise
df.subtract(df['R'], axis=0)

Q  R  S  T
0  0  0 -2 -6
1  1  0 -5 -6
2  1  0  0  1

In [149]:
# notice they auto align indices
halfrow = df.iloc[0, ::2]
halfrow

Q    8
S    6
Name: 0, dtype: int64

In [150]:
df- halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1  0.0 NaN -4.0 NaN
2 -3.0 NaN -2.0 NaN

## Handling Missing Data

### Tradeoffs in Missing Data Conventions

* *Masking approach*: separate Boolean array that globally indicates missing values

* *Sentinel approach*: Using value that indicates missing entry, such as -9999 for missing integer value, or NaN

Both have tradeoffs.

### Missing Data in Pandas

* Pandas chose to use to the NaN value, and the Python None object

#### None: Pythonic missing data

In [152]:
# only works for data type object (ie arrays of python objects)
vals1 = np.array([1, None, 3, 4])
vals1

array([1, None, 3, 4], dtype=object)

In [154]:
vals2 = np.array([1,2])
vals2

array([1, 2])

* Any operations on dtype=object arrays will be done at Python level

In [155]:
for dtype in ['object', 'int']:
    print("dtype =", dtype)
    %timeit np.arange(1E6, dtype=dtype).sum()
    print()

dtype = object
56.6 ms ± 982 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

dtype = int
815 µs ± 6.92 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)



* Use of Python objects also means if you perform aggregation like sum() when None value is present, will get an error:

In [156]:
vals1.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

#### NaN: Missing numerical data

* `NaN` (Not a Number), is a special floating-point value
* Keep in mind there is no equivalent value for integers, strings, or other types.

In [158]:
vals3 = np.array([1, np.nan, 3, 4])
# notice it is floating-point type
vals3.dtype

dtype('float64')

In [161]:
# like in R, NaN is contagious
1 + np.nan

nan

In [162]:
vals3.sum(), vals3.min()

(nan, nan)

In [164]:
# special aggregations ignore these values
np.nansum(vals3)

8.0

#### NaN and None in Pandas

In [169]:
# pandas will convert where appropriate
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [170]:
x = pd.Series(range(2), dtype=int)
x

0    0
1    1
dtype: int64

In [173]:
# automatically type casts to floating-point type
x[0] = None
x

0    NaN
1    1.0
dtype: float64

### Operating on Null Values

* Several methods for detecting, removing, and replacing null values
    + isnull()
    + notnull()
    + dropna()
    + fillna()

#### Detecting null values

In [176]:
data = pd.Series([1, np.nan, 'hello', None])
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [177]:
data[data.notnull()]

0        1
2    hello
dtype: object

#### Dropping null values

In [178]:
data.dropna()

0        1
2    hello
dtype: object

In [179]:
df = pd.DataFrame([[1, np.nan, 2],
                   [2,      3,      5],
                   [np.nan, 4,      6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

* We can only drop full rows or full columns, not single values
* by default, `dropna()` will drop all rows where any null is present

In [180]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [183]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

* You might want to drop rows or columns with *all* NA values, or majority of NA values
* Can be specified via `how` or `thresh` parameters

In [184]:
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [185]:
df.dropna(axis='columns', how='all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [187]:
# thresh lets you specify min number of non-null values
df.dropna(axis='rows', thresh=3)


0    1  2   3
1  2.0  3.0  5 NaN

#### Filling null values

* Sometimes, want to fill NA values rather than replace
* Pandas has `fillna()` method

In [190]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [191]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [192]:
# forward fill, propagate previous value forward
data.fillna(method='ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [193]:
# back-fill
data.fillna(method='bfill')

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

* DataFrames can also specify axis along which to fill

In [194]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [199]:
df.fillna(method='ffill', axis='columns')

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

## Hierarchical Indexing

* Common use for high-dimensional data is multiple index *levels* within a single index

### A Multiply Indexed Series

* Scenario where we represent 2D data into one-dimensional Series

#### The bad way

In [1]:
import numpy as np
import pandas as pd

index = [('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]

populations = populations = [33871648, 37253956,
                          18976457, 19378102,
                          20851820, 25145561]

In [2]:
pop = pd.Series(populations, index=index)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [3]:
pop[('California', 2010):('Texas', 2000)]

(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
dtype: int64

* Trying to select all values from 2010 is a problem

In [5]:
pop[[i for i in pop.index if i[1] == 2010]]

(California, 2010)    37253956
(New York, 2010)      19378102
(Texas, 2010)         25145561
dtype: int64

#### The better way: Pandas MultiIndex

In [6]:
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [9]:
index.levels

FrozenList([['California', 'New York', 'Texas'], [2000, 2010]])

In [10]:
pop = pop.reindex(index)
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [11]:
pop[:, 2010]

California    37253956
New York      19378102
Texas         25145561
dtype: int64

#### MultiIndex as extra dimension

* Could easily have used same data with DataFrame index + column
* `unstack()` method converts to conventionally indexed dataframe

In [13]:
pop_df = pop.unstack()
pop_df

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

## Methods of MultiIndex Creation

In [14]:
df = pd.DataFrame(np.random.rand(4,2),
                  index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                  columns=['data1', 'data2'])
df

data1     data2
a 1  0.601346  0.444344
  2  0.264204  0.614474
b 1  0.078782  0.027927
  2  0.493175  0.229353

In [19]:
# tuples as keys will also use MultiIndex by default
data = {('California', 2000): 33871648,
        ('California', 2010): 37253956,
        ('Texas', 2000): 20851820,
        ('Texas', 2010): 25145561,
        ('New York', 2000): 18976457,
        ('New York', 2010): 19378102}
pd.Series(data)

California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
New York    2000    18976457
            2010    19378102
dtype: int64

#### Explicit MultiIndex constructors

In [20]:
# from list of arrays
pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b'], [1, 2, 1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [23]:
# from list of tuples
pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('b', 1), ('b', 2)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [24]:
# from cartesian product of single indices
pd.MultiIndex.from_product([['a', 'b'], [1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [32]:
# passing list of labels and levels
# labels is deprecated, use codes
pd.MultiIndex(levels=[['a', 'b'], [1, 2]],
              codes=[[1, 0, 1, 0], [0, 1, 0, 1]])

MultiIndex([('b', 1),
            ('a', 2),
            ('b', 1),
            ('a', 2)],
           )

#### MultiIndex level names

* Sometimes convenient to name the levels of the `MultiIndex`
* Pass `names` argument or set after the fact

In [33]:
pop.index.names = ['state', 'year']
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

#### MultiIndex for columns

* Columns can have multiple levels as well

In [34]:
index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]],
                                       names=['year', 'visit'])

columns = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']],
                                     names=['subject', 'type'])
# mock some data
data = np.round(np.random.randn(4, 6), 1)
data[:, ::2] *= 10
data += 37

# create the DataFrame
health_data = pd.DataFrame(data, index=index, columns=columns)
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      32.0  36.8  39.0  36.9  34.0  36.0
     2      30.0  37.0  48.0  37.1  45.0  38.2
2014 1      37.0  36.6  24.0  37.3  37.0  37.5
     2      47.0  37.5  36.0  36.9  30.0  36.9

In [37]:
health_data['Guido']

type          HR  Temp
year visit            
2013 1      39.0  36.9
     2      48.0  37.1
2014 1      24.0  37.3
     2      36.0  36.9

## Indexing and Slicing a MultiIndex

* Think of indices as added dimensions

### Multiply indexed series

In [38]:
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [39]:
# access single element
pop['California', 2000]

33871648

In [40]:
# partial indexing
pop['California']

year
2000    33871648
2010    37253956
dtype: int64

In [41]:
pop.loc['California':'New York']

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
dtype: int64

In [42]:
pop[:, 2000]

state
California    33871648
New York      18976457
Texas         20851820
dtype: int64

In [43]:
pop[pop > 22000000]

state       year
California  2000    33871648
            2010    37253956
Texas       2010    25145561
dtype: int64

In [46]:
pop[['California', 'Texas']]

state       year
California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
dtype: int64

### Multiply indexed DataFrames

In [47]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      32.0  36.8  39.0  36.9  34.0  36.0
     2      30.0  37.0  48.0  37.1  45.0  38.2
2014 1      37.0  36.6  24.0  37.3  37.0  37.5
     2      47.0  37.5  36.0  36.9  30.0  36.9

In [50]:
health_data['Guido', 'HR']

year  visit
2013  1        39.0
      2        48.0
2014  1        24.0
      2        36.0
Name: (Guido, HR), dtype: float64

In [51]:
health_data.loc[:, 'Guido']

type          HR  Temp
year visit            
2013 1      39.0  36.9
     2      48.0  37.1
2014 1      24.0  37.3
     2      36.0  36.9

In [55]:
health_data.iloc[:2, :2]

subject      Bob      
type          HR  Temp
year visit            
2013 1      32.0  36.8
     2      30.0  37.0

In [57]:
# pass a tuple of multiple indices
health_data.loc[:, ('Bob', 'HR')]

year  visit
2013  1        32.0
      2        30.0
2014  1        37.0
      2        47.0
Name: (Bob, HR), dtype: float64

In [62]:
# IndexSlice object
idx = pd.IndexSlice
health_data.loc[idx[:, 1], idx[:, 'HR']]

subject      Bob Guido   Sue
type          HR    HR    HR
year visit                  
2013 1      32.0  39.0  34.0
2014 1      37.0  24.0  37.0

## Rearranging Multi-Indices

* Keys to working with multiply indexed data is knowing how to effectively transform the data

#### Sorted and unsorted indices

* Many of `MultiIndex` slicing operations will fail if index is not sorted

In [64]:
# create data where indices are not sorted
index = pd.MultiIndex.from_product([['a', 'c', 'b'], [1, 2]])
data = pd.Series(np.random.rand(6), index=index)
data.index.names = ['char', 'int']
data

char  int
a     1      0.171522
      2      0.788721
c     1      0.721043
      2      0.775471
b     1      0.819938
      2      0.365515
dtype: float64

In [66]:
try:
  data['a': 'b']
except KeyError as e:
  print(type(e))
  print(e)

<class 'pandas.errors.UnsortedIndexError'>
'Key length (1) was greater than MultiIndex lexsort depth (0)'


In [67]:
# use sort methods
data = data.sort_index()
data

char  int
a     1      0.171522
      2      0.788721
b     1      0.819938
      2      0.365515
c     1      0.721043
      2      0.775471
dtype: float64

In [68]:
data['a':'b']

char  int
a     1      0.171522
      2      0.788721
b     1      0.819938
      2      0.365515
dtype: float64

#### Stacking and unstacking indices

In [69]:
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [75]:
# level = 'state' equivalent
pop.unstack(level=0)

state  California  New York     Texas
year                                 
2000     33871648  18976457  20851820
2010     37253956  19378102  25145561

In [79]:
# level = 'year' equivalent
pop.unstack(level=1)

year            2000      2010
state                         
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

#### Index setting and resetting

* Another way to rearrange is to turn index labels into columns

In [86]:
pop_flat = pop.reset_index(name='population')
pop_flat

state  year  population
0  California  2000    33871648
1  California  2010    37253956
2    New York  2000    18976457
3    New York  2010    19378102
4       Texas  2000    20851820
5       Texas  2010    25145561

In [87]:
# go reverse and set index
pop_flat.set_index(['state', 'year'])

population
state      year            
California 2000    33871648
           2010    37253956
New York   2000    18976457
           2010    19378102
Texas      2000    20851820
           2010    25145561

## Data Aggregation on Multi-Indices

In [88]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      32.0  36.8  39.0  36.9  34.0  36.0
     2      30.0  37.0  48.0  37.1  45.0  38.2
2014 1      37.0  36.6  24.0  37.3  37.0  37.5
     2      47.0  37.5  36.0  36.9  30.0  36.9

In [90]:
# average measurements in two visits each year
data_mean = health_data.mean(level='year')
data_mean

subject   Bob        Guido         Sue      
type       HR   Temp    HR  Temp    HR  Temp
year                                        
2013     31.0  36.90  43.5  37.0  39.5  37.1
2014     42.0  37.05  30.0  37.1  33.5  37.2

In [93]:
# mean among columns
data_mean.mean(axis='columns', level='type')

type         HR       Temp
year                      
2013  38.000000  37.000000
2014  35.166667  37.116667

## Combining Datasets: Concat and Append